# Generated by Django 4.1.2 on 2023-02-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelike',
            old_name='dt_linked',
            new_name='dt_liked',
        ),
    ]
