# Generated by Django 4.1.2 on 2023-02-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_dt_linked_articlelike_dt_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hilight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
