# Generated by Django 4.1.2 on 2023-02-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_hilight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hilight',
            new_name='highlight',
        ),
    ]
