# Generated by Django 4.1.2 on 2023-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='iskecian',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
